In [21]:
import random as rand
import numpy as np

In [214]:
#in Blender 3D view, 1 unit scale = 0.01 km
class point:
    def __init__(self, x,y,z):
        self.x = x
        self.y = y
        self.z = z
        
class body():
    #initializing a body with mass, velocity, and radius
    def __init__(self, location, mass, velocity, name=""):
        self.location=location
        self.mass=mass
        self.velocity=velocity
#         self.radius=radius
        self.name=name
    
#     def calc_acceleration(bodies, body_index):
#         #gravitaional constant 6.67430 (± 0.00015) x 10^-11 kg-1 m3 s-2
#         G=6.674e-20 #km3 kg-1 s-2
#         target = bodies[body_index]
#         acceleration=point(0,0,0)
#         for body in enumerate(bodies):
#             if body_index != index
        
    def calc_velocity(self, timestep):
        self.velocity.x += self.acceleration.x * timestep
        self.velocity.y += self.acceleration.y * timestep
        self.velocity.z += self.acceleration.z * timestep
        
        
    def update_location(self, timestep):
        self.location.x += self.velocity.x * timestep
        self.location.y += self.velocity.y * timestep
        self.location.z += self.velocity.y * timestep

In [49]:
pos=np.array(4,3)
# positions r = [x,y,z] for all particles
x = pos[0]
y = pos[1]
z = pos[2]

# matrix that stores all pairwise particle separations: r_j - r_i
dx = x.T - x
dy = y.T - y
dz = z.T - z


TypeError: data type not understood

In [146]:
r1=np.random.rand(3);r1
r2=np.random.rand(3);r2
r3=np.random.rand(3);r3

array([ 0.27898583,  0.07043014,  0.66433604])

In [127]:
pos=np.zeros((3,3));pos

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [149]:
pos[0,:],pos[1,:],pos[2,:]=r1,r2,r3
pos

array([[ 0.35392876,  0.23472561,  0.48376597],
       [ 0.23602001,  0.51476951,  0.43839126],
       [ 0.27898583,  0.07043014,  0.66433604]])

In [161]:
x,y,z=pos[:,0:1],pos[:,1:2],pos[:,2:3]
z

array([[ 0.48376597],
       [ 0.43839126],
       [ 0.66433604]])

In [169]:
pos[:,2]

array([ 0.48376597,  0.43839126,  0.66433604])

In [167]:
z.T

array([[ 0.48376597,  0.43839126,  0.66433604]])

In [168]:
z.T - z

array([[ 0.        , -0.04537471,  0.18057006],
       [ 0.04537471,  0.        ,  0.22594477],
       [-0.18057006, -0.22594477,  0.        ]])

In [162]:
dx = x.T - x
dy = y.T - y
dz = z.T - z

In [208]:
r=np.zeros((3,3))
m=np.zeros(3)
a=np.zeros((3,3))
G_const = 6.67408e-11 #m3 kg-1 s-2
# acceleration = point(0,0,0)
a=0
for i in range(1,3):
    for j in range(1,3):
        m=(5,3,2)
        if i != j:
            r[i,j]=np.sqrt((x[i]-x[j]**2) + (y[i]+y[j]**2) + (z[i]+z[j]**2))
            const=m[j] /r[i,j]**3 #times G
            ax+=const * (x[j]-x[i])
            ay+=const * (y[j]-y[i])
            az+=const * (z[j]-z[i])
            a[i,j]=
# return 

TypeError: 'int' object does not support item assignment

In [216]:
#planet data (location (m), mass (kg), velocity (m/s)
sun = {"location":point(0,0,0), "mass":2e30, "velocity":point(0,0,0)}
mercury = {"location":point(0,5.7e10,0), "mass":3.285e23, "velocity":point(47000,0,0)}
venus = {"location":point(0,1.1e11,0), "mass":4.8e24, "velocity":point(35000,0,0)}
earth = {"location":point(0,1.5e11,0), "mass":6e24, "velocity":point(30000,0,0)}
mars = {"location":point(0,2.2e11,0), "mass":2.4e24, "velocity":point(24000,0,0)}
# jupiter = {"location":point(0,7.7e11,0), "mass":1e28, "velocity":point(13000,0,0)}
# saturn = {"location":point(0,1.4e12,0), "mass":5.7e26, "velocity":point(9000,0,0)}
# uranus = {"location":point(0,2.8e12,0), "mass":8.7e25, "velocity":point(6835,0,0)}
# neptune = {"location":point(0,4.5e12,0), "mass":1e26, "velocity":point(5477,0,0)}
# pluto = {"location":point(0,3.7e12,0), "mass":1.3e22, "velocity":point(4748,0,0)}

if __name__ == "__main__":

    #build list of planets in the simulation, or create your own
    bodies = [
        sphere( location = sun["location"], mass = sun["mass"], velocity = sun["velocity"], name = "sun"),
        sphere( location = earth["location"], mass = earth["mass"], velocity = earth["velocity"], name = "earth"),
        sphere( location = mars["location"], mass = mars["mass"], velocity = mars["velocity"], name = "mars"),
        sphere( location = venus["location"], mass = venus["mass"], velocity = venus["velocity"], name = "venus"),
        ]
    

In [ ]:
def create_sphere(radius, distance_to_sun, obj_name):
    # instantiate a UV sphere with a given
    # radius, at a given distance from the
    # world origin point
    bpy.ops.mesh.primitive_uv_sphere_add(
        radius=radius,
        location=(distance_to_sun, 0, 0),
        scale=(1, 1, 1)
    )
    # get object
    obj = bpy.context.object
    # rename the object
    obj.name = obj_name
    # return the object reference
    return obj

# def add_sphere(name, location):
#     """Add smooth sphere to current scene at given location
#     name -- name for new sphere
#     location -- location for the new sphere
#     """
#     # add object
# #     bpy.ops.mesh.primitive_uv_sphere_add(
# #         segments=48, ring_count=24, size=1.0,
# #         location=location, rotation=[0,0,0])
#     # get object
#     obj = bpy.context.object
#     # set name and smooth shading
#     obj.name = name
#     bpy.ops.object.shade_smooth()
       
# #     print("Sphere '%s' created." % name)
   
#     return obj