In [1]:
import random as rand
import numpy as np
import matplotlib.pyplot as plt

in Blender 3D view, 1 unit scale = 0.01 km ? need to confirm scaling.

In [4]:
class point:
    def __init__(self, x,y,z):
        self.x = x
        self.y = y
        self.z = z

In [115]:
def calc_velocity(self, timestep):
#         acceleration = 
    self.velocity.x += self.acceleration.x * timestep
    self.velocity.y += self.acceleration.y * timestep
    self.velocity.z += self.acceleration.z * timestep


def update_loc(self, timestep):
    self.location.x += self.velocity.x * timestep
    self.location.y += self.velocity.y * timestep
    self.location.z += self.velocity.y * timestep

def advance_sim(self, timestep):
    self.new_location = []
    for i, body in enumerate(self.bodies):
        body.update_loc(timestep)
        self.new_location.append(body.location)
    

In [95]:
class body():
    """
    initializing a body with mass, velocity, and location
    """
    def __init__(self, location, mass, velocity, name=""):
        self.location=location
        self.mass=mass
        self.velocity=velocity
#         self.radius=radius
        self.name=name
#gravitaional constant 6.67430 (± 0.00015) x 10^-11 kg-1 m3 s-2
G=6.674e-20 #km3 kg-1 s-2
def calculate_acceleration(bodies,ref_index):
    """
    calculates the gravitational acceleration that the reference target body i
    experiences due to the other perturbing bodies j
    a_g = F_g/m_i = -Gm_j/r_ij^3 
    """
    target=bodies[ref_index]
    acceleration=point(0,0,0)
    for other_index, body in enumerate(bodies):
        if ref_index != other_index:
            r = np.sqrt(((target.location.x -body.location.x)**2 + (target.location.y -body.location.y)**2 + (target.location.z -body.location.z)**2))
            a_g = -G * body.mass / r**3
            acceleration.x += a_g * (body.location.x-target.location.x) 
            acceleration.y += a_g * (body.location.y-target.location.y)
            acceleration.z += a_g * (body.location.z-target.location.z)
#     print(target.name,acceleration.y)
    return acceleration   
def calculate_velocity(bodies,timestep):
    """
    calculates the velocity caused by the gravitational acceleration
    """
     for ref_index, target in enumerate(bodies):
            acceleration=calc_acceleration(bodies,ref_index)
            target.velocity.x += target.acceleration.x * timestep
            target.velocity.y += target.acceleration.y * timestep
            target.velocity.z += target.acceleration.z * timestep
            
def update_location(bodies,timestep):
    for target in bodies:
        target.location.x += target.velocity.x * timestep
        target.location.y += target.velocity.y * timestep
        target.location.z += target.velocity.y * timestep

def advance(bodies,timestep):
#     new_loc =[]
    for ref_index, target in enumerate(bodies):
        calculate_acceleration(bodies,ref_index)
        calculate_velocity(bodies,timestep)
        target.update_location(bodies,timestep)
        
        

In [4]:
sum(pos)

NameError: name 'pos' is not defined

In [113]:
pos=np.array(4,3)
# positions r = [x,y,z] for all particles
x = pos[0]
y = pos[1]
z = pos[2]

# matrix that stores all pairwise particle separations: r_j - r_i
dx = x.T - x
dy = y.T - y
dz = z.T - z


NameError: name 'Float64' is not defined

In [146]:
r1=np.random.rand(3);r1
r2=np.random.rand(3);r2
r3=np.random.rand(3);r3

array([ 0.27898583,  0.07043014,  0.66433604])

In [127]:
pos=np.zeros((3,3));pos

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [149]:
pos[0,:],pos[1,:],pos[2,:]=r1,r2,r3
pos

array([[ 0.35392876,  0.23472561,  0.48376597],
       [ 0.23602001,  0.51476951,  0.43839126],
       [ 0.27898583,  0.07043014,  0.66433604]])

In [161]:
x,y,z=pos[:,0:1],pos[:,1:2],pos[:,2:3]
z

array([[ 0.48376597],
       [ 0.43839126],
       [ 0.66433604]])

In [169]:
pos[:,2]

array([ 0.48376597,  0.43839126,  0.66433604])

In [167]:
z.T

array([[ 0.48376597,  0.43839126,  0.66433604]])

In [168]:
z.T - z

array([[ 0.        , -0.04537471,  0.18057006],
       [ 0.04537471,  0.        ,  0.22594477],
       [-0.18057006, -0.22594477,  0.        ]])

In [162]:
dx = x.T - x
dy = y.T - y
dz = z.T - z

In [105]:
r=np.zeros((3,3))
m=np.zeros(3)
a=np.zeros((3,3))
G_const = 6.67408e-11 #m3 kg-1 s-2
# acceleration = point(0,0,0)
a=0
for i in range(1,3):
    for j in range(1,3):
        m=(5,3,2)
        if i != j:
            r[i,j]=np.sqrt((x[i]-x[j]**2) + (y[i]+y[j]**2) + (z[i]+z[j]**2))
            a_g=m[j] /r[i,j]**3 #times G
            ax+=const * (x[j]-x[i])
            ay+=const * (y[j]-y[i])
            az+=const * (z[j]-z[i])
#             a[i,j]=
# return 

NameError: name 'x' is not defined

### Testing

In [7]:
#planet data (location (m), mass (kg), velocity (m/s)
sun = {"location":point(0,0,0), "mass":2e30, "velocity":point(0,0,0)}
mercury = {"location":point(0,5.7e10,0), "mass":3.285e23, "velocity":point(47000,0,0)}
venus = {"location":point(0,1.1e11,0), "mass":4.8e24, "velocity":point(35000,0,0)}
earth = {"location":point(0,1.5e11,0), "mass":6e24, "velocity":point(30000,0,0)}
mars = {"location":point(0,2.2e11,0), "mass":2.4e24, "velocity":point(24000,0,0)}
# jupiter = {"location":point(0,7.7e11,0), "mass":1e28, "velocity":point(13000,0,0)}
# saturn = {"location":point(0,1.4e12,0), "mass":5.7e26, "velocity":point(9000,0,0)}
# uranus = {"location":point(0,2.8e12,0), "mass":8.7e25, "velocity":point(6835,0,0)}
# neptune = {"location":point(0,4.5e12,0), "mass":1e26, "velocity":point(5477,0,0)}
# pluto = {"location":point(0,3.7e12,0), "mass":1.3e22, "velocity":point(4748,0,0)}

if __name__ == "__main__":

    #build list of planets in the simulation, or create your own
    bodies = [
        body( location = sun["location"], mass = sun["mass"], velocity = sun["velocity"], name = "sun"),
        body( location = earth["location"], mass = earth["mass"], velocity = earth["velocity"], name = "earth"),
        body( location = mars["location"], mass = mars["mass"], velocity = mars["velocity"], name = "mars"),
        body( location = venus["location"], mass = venus["mass"], velocity = venus["velocity"], name = "venus"),
        ]
    

In [20]:
list(enumerate(bodies))

[(0, <__main__.body at 0x108633e48>),
 (1, <__main__.body at 0x108633ef0>),
 (2, <__main__.body at 0x108633f28>),
 (3, <__main__.body at 0x108633f60>)]

In [19]:
def create_sphere(radius, distance_to_sun, obj_name):
    # instantiate a UV sphere with a given
    # radius, at a given distance from the
    # world origin point
    bpy.ops.mesh.primitive_uv_sphere_add(
        radius=radius,
        location=(distance_to_sun, 0, 0),
        scale=(1, 1, 1)
    )
    # get object
    obj = bpy.context.object
    # rename the object
    obj.name = obj_name
    # return the object reference
    return obj

# def add_sphere(name, location):
#     """Add smooth sphere to current scene at given location
#     name -- name for new sphere
#     location -- location for the new sphere
#     """
#     # add object
# #     bpy.ops.mesh.primitive_uv_sphere_add(
# #         segments=48, ring_count=24, size=1.0,
# #         location=location, rotation=[0,0,0])
#     # get object
#     obj = bpy.context.object
#     # set name and smooth shading
#     obj.name = name
#     bpy.ops.object.shade_smooth()
       
# #     print("Sphere '%s' created." % name)
   
#     return obj